### ISSUE TITLE
segmentation violation on i/o timeout

### ISSUE THREAD

**Issue by n0madic** [kubewall/kubewall#34]
When I tried to connect to an unavailable cluster I got an error and crashed
```
reflector.go:158] "Unhandled Error" err="k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get \"https://144.24.174.16:6443/api/v1/namespaces?limit=500&resourceVersion=0\": dial tcp 144.24.174.16:6443: i/o timeout" logger="UnhandledError"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1021f9bf0]

goroutine 9 [running]:
github.com/kubewall/kubewall/backend/container.(*container).MetricClient(0x1022f5f95?, {0x140004bf0d8?, 0x14005a86510?}, {0x140004bf0e7, 0x6})
	github.com/kubewall/kubewall/backend/container/container.go:133 +0x50
github.com/kubewall/kubewall/backend/handlers/workloads/pods.GetPodsMetricsList(0x140030c0000)
	github.com/kubewall/kubewall/backend/handlers/workloads/pods/pods.go:119 +0x124
github.com/kubewall/kubewall/backend/handlers/workloads/pods.(*PodsHandler).DeploymentsPods(0x140030c0000, {0x102c129e8, 0x14000285ae0})
	github.com/kubewall/kubewall/backend/handlers/workloads/pods/deployments.go:29 +0x29c
github.com/kubewall/kubewall/backend/handlers/workloads/pods.NewPodsHandler.func1()
	github.com/kubewall/kubewall/backend/handlers/workloads/pods/pods.go:87 +0x28
github.com/kubewall/kubewall/backend/event.(*EventProcessor).processEvents(0x140004a9488)
	github.com/kubewall/kubewall/backend/event/event.go:45 +0x138
github.com/kubewall/kubewall/backend/event.(*EventProcessor).Run(...)
	github.com/kubewall/kubewall/backend/event/event.go:35
created by github.com/kubewall/kubewall/backend/container.NewContainer in goroutine 1
	github.com/kubewall/kubewall/backend/container/container.go:73 +0x2ac
```

**Comment by abhimanyu003** [comment]
we have added a middleware that will prevent this for happening. Once thanks for your report, also let us know if you face anything.
